Mac App basically done, at least as far as a shell script version goes.
Signed-off-by: Natalie Spencer <nmspencer@icloud.com>

diff --git a/client/macos/Thoth-Backup.app/Contents/Resources/script b/client/macos/Thoth-Backup.app/Contents/Resources/script
--- a/client/macos/Thoth-Backup.app/Contents/Resources/script
+++ b/client/macos/Thoth-Backup.app/Contents/Resources/script
@@ -20,6 +20,7 @@ DATE="$(which date)"
 GZIP="$(which gzip)"
 HOSTNAME_CMD="$(which hostname)"
 RSYNC="$(which rsync)"
+SED="$(which sed)"
 SSH="$(which ssh)"
 WHOAMI="$(which whoami)"
 
@@ -32,6 +33,9 @@ USER_DIR="/Users/$LOCAL_USERNAME"
 ARCHIVE_DIR="$USER_DIR/ThothArchive"
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+
+SERVICE="$SCRIPT_DIR/service/io.zyradyl.thoth-backup.service.plist"
+SCRIPT="$SCRIPT_DIR/script"
 
 EXCLUSIONS="$SCRIPT_DIR/exclusions/exclusions"
 FIRST_RUN="$SCRIPT_DIR/triggers/FirstRun"
@@ -56,56 +60,21 @@ function ctrl_c {
 #
 # Global Functions
 #
-function sync_background {
+function syncronize {
   ssh="$SSH -i $BACKUP_KEY"
-  source="$user_dir"
+  source="$USER_DIR"
   dest="$BACKUP_USER@$BACKUP_SERVER:/home/$BACKUP_USER/BACKUP"
-  rsync_base="$RSYNC -av --exclude-from=$exclusions --ignore-errors --delete -e"
+  rsync_base="$RSYNC -av --exclude-from=$EXCLUSIONS --ignore-errors --delete -e"
   backup_cmd="$rsync_base $ssh $source $dest"
-  $backup_cmd > $log_file 2>&1
-  $GZIP $log_file
-}
-function sync_foreground {
-  ssh="$SSH -i $BACKUP_KEY"
-  source="$user_dir"
-  dest="$backup_user@$BACKUP_SERVER:/home/$backup_user/BACKUP"
-  rsync_base="$RSYNC --progress -a --exclude-from=$exclusions --ignore-errors --delete -e"
-  backup_cmd="$rsync_base $ssh $source $dest"
-  $backup_cmd
+  $backup_cmd > $LOG_FILE 2>&1
+  $GZIP $LOG_FILE
 }
 
 #
-# Stage 1 - Check if the Package is Correctly Set up
-#
-
-if [ ! -f $backup_key ]; then
-    printf "\n\nFATAL ERROR:\n\n"
-    printf "Your backup key is either not present or incorrectly named.\n"
-    printf "Please make sure the key directory contains a private key file\n"
-    printf "given to you by the server operator. It should have come from\n"
-    printf "the operator correctly named. If the file is there, contact the\n"
-    printf "operator because your key is not correct and you will need to be\n"
-    printf "registered again on the server.\n"
-    exit 1
-fi
-
-if [ $(stat -f %A $backup_key) != 600 ]; then
-  printf "\n\nINFO:\n\n"
-  printf "Your backup key does not have the correct permissions to be used\n"
-  printf "with ssh. The permissions will be updated to ensure success.\n"
-  $CHMOD 600 $backup_key
-fi
-
-#
-# Stage 2 - Check if this is our first run.
-#
-#   + We look for a file in the "trigger" directory called "FirstRun"
-#   + If it doesn't exist, we assume this is the first run of the program.
-#   + If this is the first run, create the Archive Directory and add it to
-#     the exclusion list. While the archive is not yet functional, it is
-#     better to plan ahead.
+# Execute
 #
 if [ ! -f $FIRST_RUN ]; then
+
   printf "First Run Detected, Initializing...\n"
   printf "Welcome to the Thoth Backup System!\n\n"
   printf "Thank you for your interest in this backup software. It should be\n"
@@ -118,18 +87,75 @@ if [ ! -f $FIRST_RUN ]; then
   printf "long time. A program will be used to prevent your system from\n"
   printf "sleeping. You can cancel this process at any time, and it will\n"
   printf "start from where it left off.\n\n"
-  read -p "Press enter to continue."
+
+  if [ ! -f $BACKUP_KEY ]; then
+      printf "\n\nFATAL ERROR:\n"
+      printf "Your backup key is either not present or incorrectly named.\n"
+      printf "Please make sure the key directory contains a private key file\n"
+      printf "given to you by the server operator. It should have come from\n"
+      printf "the operator correctly named. If the file is there, contact the\n"
+      printf "operator because your key is not correct and you will need to be\n"
+      printf "registered again on the server.\n\n"
+      exit 1
+  fi
+
+  if [ $(stat -f %A $BACKUP_KEY) != 600 ]; then
+    printf "\nINFO:\n"
+    printf "Your backup key does not have the correct permissions to be used\n"
+    printf "with ssh. The permissions will be updated to ensure success.\n"
+    printf "\n\n"
+    $CHMOD 600 $BACKUP_KEY
+  fi
+
   if [ ! -d "$ARCHIVE_DIR" ]; then
+    printf "\nINFO:\n"
+    printf "You do not currently have a ThothArchive directory. One will now\n"
+    printf "be created for you.\n"
+    printf "\n\n"
     mkdir $ARCHIVE_DIR
   fi
+
   if [ ! -f $EXCLUSIONS ]; then
+    printf "\nINFO:\n"
+    printf "Your exclusions file is not currently set up. One will now be\n"
+    printf "established with the default values. Please do not ever remove\n"
+    printf "the archive directory from the exclusions list."
     echo "$ARCHIVE_DIR" > $EXCLUSIONS
   fi
+
+  printf "\n\n\nWARNING:\n"
+  printf "You must now allow Thoth-Backup Full Disk Access. In a moment, a\n"
+  printf "System Preferences Pane will open. You must do the following:\n"
+  printf "1. Find \"Full Disk Access\" in the left selection box and click it\n"
+  printf "2. Click the lock at the bottom to authenticate to the system\n"
+  printf "3. Enter your system password\n"
+  printf "4. Drag the Thoth-Backup program from applications into FDA\n"
+  printf "5. Make sure Thoth-Backup is checked\n"
+  printf "6. Click the lock to deauthenticate\n"
+  printf "\nOnce this is complete, exit out of this instance of the program\n"
+  printf "and re-open it to begin the initial syncronization.\n"
+
   touch $FIRST_RUN
+  open /System/Library/PreferencePanes/Security.prefPane
+  open /applications
+
+  exit 1
+
 elif [ ! -f $INITIAL_SYNC ]; then
-  printf "\n\nThe initial syncronization and setup will now start.\n"
-  read -p "Press enter to continue."
-  sync_foreground
+  printf "Welcome back!\n"
+  printf "\n\nThe initial syncronization will now continue.\n"
+  syncronize
+  printf "Initial Syncronization is now complete!\n"
+  printf "Now installing the backup service...\n"
+
+  # TODO: Clean this up
+  $SED -i '' "s~REPLACED_BY_INSTALLATION~$SCRIPT~g" $SERVICE
+  cp "$SERVICE" "$USER_DIR/Library/LaunchAgents/"
+  launchctl load -w "$USER_DIR/Library/LaunchAgents/io.zyradyl.thoth-backup.service.plist"
+
+  printf "Thank you for choosing Thoth Backup!\n"
+  touch $INITIAL_SYNC
+
 else
-  sync_background
+  syncronize
 fi
